language: go
go: 1.17.x
notifications:
  email: true
services:
  - docker

stages:
  - build
  - test

sudo: true

before_install: []

install: []

before_script:
  - sudo apt-get install libgl1-mesa-dev libxinerama-dev libxcursor-dev libxrandr-dev -y
  - go env -w GO111MODULE="on"
  - git lfs pull
  - export COVERAGE_REPORT=$(pwd)/.coverage.txt

addons:
  apt:
    update: true

jobs:
  include:
    - stage: build
      script:
        - cd binaries
        - go mod tidy
        - make
    - stage: test
      script: 
        - cd binaries
        - go test ./... -coverprofile=${COVERAGE_REPORT} -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f ${COVERAGE_REPORT} -t ${CODECOV_TOKEN}
