language: go
go: 1.17.x
notifications:
  email: true
services:
  - docker

stages:
  - build
  - test

sudo: true

before_install: []

install: []

before_script:
  - go env -w GO111MODULE="on"
  - git lfs pull
  - go mod tidy
  - export COVERAGE_REPORT=$(pwd)/.coverage.txt

jobs:
  include:
    - stage: build
      script:
        - cd binaries
        - make
    - stage: test
      script: 
        - cd binaries
        - go test ./... -coverprofile=${COVERAGE_REPORT} -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f ${COVERAGE_REPORT} -t ${CODECOV_TOKEN}
