language: go
go: 1.17.x
notifications:
  email: true
services:
  #- docker

stages:
  - build

sudo: true

before_install:

install:

before_script:
  - go env -w GO111MODULE="on"
  - git lfs pull
  - go mod tidy
  - export COVERAGE_REPORT=.coverage.txt

jobs:
  include:
    - stage: build
      script: make cmd
