# Rime schema
# encoding: utf-8


# 方案说明
schema:
  schema_id: ahaooahaz_pinyin_simp
  name: 阿昊拼音
  version: "2024-02-25"
  author:
    - ahaooahaz
  description: |
    阿昊拼音
    https://github.com/ahaooahaz/Annal/configs/rime
  dependencies:

# 开关
# reset: 默认状态。注释掉后，切换窗口时不会重置到默认状态。
# states: 方案选单显示的名称。可以注释掉，仍可以通过快捷键切换。
# abbrev: 默认的缩写取 states 的第一个字符，abbrev 可自定义一个字符
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中, A ]
  - name: ascii_punct  # 中英标点
    states: [ ¥, $ ]
  - name: full_shape
    states: ["半角", "全角"]
  - name: zh_simp
    reset: 1
    states: [ 简, 繁 ]
  - name: emoji_suggestion
    reset: 1
    states: ["🈚︎", "🈶️"]
  - options: [utf8, gbk, gb2312]
    reset: 0
    states: ["UTF-8", GBK, GB2312]


engine:
  filters:
    - simplifier
    - simplifier@emoji_suggestion
    - uniquifier                                    # 去重
    - "charset_filter@gbk"
    - single_char_filter  
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator@custom_phrase
    - reverse_lookup_translator
    - script_translator
    - lua_translator@date_translator    # 时间、日期、星期

# Lua 配置: 日期、时间、星期、ISO 8601、时间戳的触发关键字
date_translator:
  date: date       # 日期： 2022-11-29
  time: time       # 时间： 18:13
  week: week       # 星期： 星期二
  datetime: datetime   # ISO 8601： 2022-11-29T18:13:11+08:00
  timestamp: timestamp  # 时间戳： 1669716794


translator:
  dictionary: rime_ice # 挂载词库 rime_ice.dict.yaml
  spelling_hints: 8           # corrector.lua ：为了让错音错字提示的 Lua 同时适配全拼双拼，将拼音显示在 comment 中
  always_show_comments: true  # corrector.lua ：Rime 默认在 preedit 等于 comment 时取消显示 comment，这里强制一直显示，供 corrector.lua 做判断用。
  initial_quality: 1.2        # 拼音的权重应该比英文大
  preedit_format:             # preedit_format 影响到输入框的显示和“Shift+回车”上屏的字符
    - xform/([jqxy])v/$1u/    # 显示为 ju qu xu yu
    # - xform/([nl])v/$1ü/    # 显示为 nü lü
    # - xform/([nl])ue/$1üe/  # 显示为 nüe lüe
    - xform/([nl])v/$1v/      # 显示为 nv lv
    - xform/([nl])ue/$1ve/    # 显示为 nve lve


# 自定义短语：custom_phrase.txt
custom_phrase:
  dictionary: ""
  user_dict: custom_phrase  # 可以修改这里，改成自己的 txt 文件
  db_class: stabledb        # 只读数据库，无法动态调频；设为 tabledb 可以动态调频
  enable_completion: false  # 补全提示
  enable_sentence: false    # 禁止造句
  initial_quality: 99       # custom_phrase 的权重应该比 pinyin 和 melt_eng 大


emoji_suggestion:
  inherit_comment: false
  opencc_config: emoji.json
  option_name: emoji_suggestion
  tags: abc
  tips: all

# 标点符号
# punctuator 下面有三个子项：
#   full_shape 全角标点映射
#   half_shape 半角标点映射
#   symbols    Rime 的预设配置是以 '/' 前缀开头输出一系列字符，自定义的 symbols_v.yaml 修改成了 'v' 开头。
punctuator:
  full_shape:
    __include: default:/punctuator/full_shape  # 从 default.yaml 导入配置
  half_shape:
    __include: default:/punctuator/half_shape  # 从 default.yaml 导入配置
  symbols:
    __include: symbols_v:/symbols              # 从 symbols_v.yaml 导入配置

key_binder:
  import_preset: default
  search: "`"             # 辅码引导符，要添加到 speller/alphabet


# 处理符合特定规则的输入码，如网址、反查
recognizer:
  import_preset: default  # 从 default.yaml 继承通用的
  patterns:  # 再增加方案专有的：
    punct: "^v([0-9]|10|[A-Za-z]+)$"    # 响应 symbols_v.yaml 的 symbols，用 'v' 替换 '/'
    radical_lookup: "^uU[a-z]+$"        # 响应部件拆字的反查，与 radical_lookup/prefix 匹配
    unicode: "^U[a-f0-9]+"              # 脚本将自动获取第 2 个字符 U 作为触发前缀，响应 lua_translator@unicode，输出 Unicode 字符
    number: "^R[0-9]+[.]?[0-9]*"        # 脚本将自动获取第 2 个字符 R 作为触发前缀，响应 lua_translator@number_translator，数字金额大写
    gregorian_to_lunar: "^N[0-9]{1,8}"  # 脚本将自动获取第 2 个字符 N 作为触发前缀，响应 lua_translator@lunar，公历转农历，输入 N20240115 得到「二〇二三年腊月初五」
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    reverse_lookup: "`[a-z]*'?$"

reverse_lookup:
  comment_format:
    - "xform/([nl])v/$1ü/"
  dictionary: stroke
  enable_completion: true
  preedit_format:
    - "xlit/hspnz/一丨丿丶乙/"
  prefix: "`"
  suffix: "'"
  tips: "〔筆畫〕"


# 部件拆字反查
radical_lookup:
  tag: radical_lookup
  dictionary: radical_pinyin
  enable_user_dict: false
  prefix: "uU"  # 反查前缀（反查时前缀会消失影响打英文所以设定为两个字母，或可改成一个非字母符号），与 recognizer/patterns/radical_lookup 匹配
  tips: "  〔拆字〕"
  comment_format:
    - erase/^.*$//
# 部件拆字滤镜
radical_reverse_lookup:
  tags: [ radical_lookup ]
  # dictionary 为拼音标注来源。目前是显示本方案词库的注音，可去部件拆字方案下载更全的、带声调的、已编译好的词典
  # https://github.com/mirtlecn/rime-radical-pinyin?tab=readme-ov-file#%E5%8F%8D%E6%9F%A5%E5%B8%A6%E5%A3%B0%E8%B0%83%E6%B3%A8%E9%9F%B3
  dictionary: ahaooahaz.extended
  # comment_format:     # 自定义 comment，例如在左右加上括号
  #  - xform/^/(/
  #  - xform/$/)/


speller:
  # 如果不想让什么标点直接上屏，可以加在 alphabet，或者编辑标点符号为两个及以上的映射
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA`
  # initials 定义仅作为始码的按键，排除 ` 让单个的 ` 可以直接上屏
  initials: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"  # 第一位<空格>是拼音之间的分隔符；第二位<'>表示可以手动输入单引号来分割拼音。
  algebra:
    - "erase/^xx$/"
    - "abbrev/^([a-z]).+$/$1/"
    - "abbrev/^([zcs]h).+$/$1/"
    - "derive/^([nl])ve$/$1ue/"
    - "derive/^([jqxy])u/$1v/"
    - "derive/un$/uen/"
    - "derive/ui$/uei/"
    - "derive/iu$/iou/"
    - "derive/([aeiou])ng$/$1gn/"
    - "derive/([dtngkhrzcs])o(u|ng)$/$1o/"
    - "derive/ong$/on/"
    - "derive/ao$/oa/"
    - "derive/([iu])a(o|ng?)$/a$1$2/"


simplifier:
  option_name: zh_simp


##########################################################
# # 次翻译器，英文
# melt_eng:
#   dictionary: melt_eng     # 挂载词库 melt_eng.dict.yaml
#   enable_sentence: false   # 禁止造句
#   enable_user_dict: false  # 禁用用户词典
#   initial_quality: 1.1     # 初始权重
#   comment_format:          # 自定义提示码
#     - xform/.*//           # 清空提示码

# # 中英混合词汇
# cn_en:
#   dictionary: ""
#   user_dict: en_dicts/cn_en
#   db_class: stabledb
#   enable_completion: true
#   enable_sentence: false
#   initial_quality: 0.5
#   comment_format:
#     - xform/^.+$//

# # Emoji
# emoji:
#   option_name: emoji
#   opencc_config: emoji.json
#   inherit_comment: false  # 在 corrector.lua 及反查中，emoji 返回空注释

# # 简繁切换
# traditionalize:
#   option_name: traditionalization
#   opencc_config: s2t.json  # s2t.json | s2hk.json | s2tw.json | s2twp.json
#   tips: none               # 转换提示: all 都显示 | char 仅单字显示 | none 不显示。
#   tags: [ abc, number, gregorian_to_lunar ]  # 限制在对应 tag，不对其他如反查的内容做简繁转换