name: Unitest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.17.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: |
          set -x
          cd binaries && go mod tidy && cd -
      - name: Build
        run: |
          set -x
          make -C binaries
      - name: Test
        run: |
          set -x
          cd binaries && go test ./... -coverprofile=.coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./binaries/.coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
